linux_task:
  container:
    dockerfile: .cirrus-docker/Dockerfile
  env:
    matrix:
      - COMPILER: g++-10
        CXXSTD: 11
        SANITIZE: true

      - COMPILER: g++-10
        CXXSTD: 14
        SANITIZE: true

      - COMPILER: g++-10
        CXXSTD: 17
        SANITIZE: true

      - COMPILER: g++-10
        CXXSTD: 20
        SANITIZE: true

      - COMPILER: g++-9
        CXXSTD: 11
        SANITIZE: true

      - COMPILER: g++-9
        CXXSTD: 14
        SANITIZE: true

      - COMPILER: g++-9
        CXXSTD: 17
        SANITIZE: true

      - COMPILER: g++-9
        CXXSTD: 20
        SANITIZE: true

  build_script:
    - mkdir build
    - cd build
    - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" -DCMAKE_CXX_STANDARD=${CXXSTD} -DCXX_STDLIB=${STDLIB} -DSANITIZE=${SANITIZE} ..
    - make VERBOSE=1 self_test
    - make VERBOSE=1 custom_recursive_mutex
  test_script:
    - cd build
    - make run_self_test
    - |
      make run_coverage
