linux_task:
  container:
    dockerfile: .cirrus-docker/Dockerfile
  env:
    matrix:
      - COMPILER: clang++-10
        CXXSTD: 14
        STDLIB: "libc++"
        LDFLAGS: "-fuse-ld=gold -lc++abi"
        SANITIZE: true
  build_script:
    - mkdir build
    - cd build
    - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" -DCMAKE_CXX_STANDARD=${CXXSTD} -DCXX_STDLIB=${STDLIB} -DSANITIZE=${SANITIZE} ..
    - make VERBOSE=1 -j 4 self_test
    - make VERBOSE=1 custom_recursive_mutex
  test_script:
    - cd build
    - make run_self_test && make run_coverage
